services:
  database:
    image: mysql:7
    container_name: alura_food
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql




volumes:
  mysql_data: